### ISSUE TITLE
Lack of a License [Urgent]

### ISSUE THREAD

**Issue by ThatGeekyWeeb** [Prodiginus/Frosted#3]
Quote [no-permission](https://choosealicense.com/no-permission/)
This repo contains no License

*If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.*

Without a License, users using or forking the repo, *may* be doin so illegally, please consider adding a License, on that allows the community to continue to enjoy your work!

**Comment by ThatGeekyWeeb** [comment]
The ISC License may be a simple/easy and good choice

>[ISC](https://choosealicense.com/licenses/isc/)

**Comment by Prodiginus** [comment]
Added my personal favorite license
